"""initial schema baseline

Revision ID: 6edf4ae85a50
Revises: 
Create Date: 2026-05-04 19:20:16.967088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edf4ae85a50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.alter_column('rarity',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'common'"))

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bookmarks_mission_id'))

    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_completions_mission_id'))
        batch_op.drop_index(batch_op.f('idx_completions_submitted_at'))

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'english'"))
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.drop_index(batch_op.f('idx_missions_date'))
        batch_op.drop_index(batch_op.f('idx_missions_review'))
        batch_op.drop_index(batch_op.f('idx_missions_skill_id'))
        batch_op.drop_index(batch_op.f('idx_missions_status'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_created_at'))
        batch_op.drop_index(batch_op.f('idx_notifications_read'))

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('api_provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'openai'"))
        batch_op.alter_column('theme',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'light'"))
        batch_op.alter_column('display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Hari'"))
        batch_op.alter_column('avatar',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'⚡'"))
        batch_op.alter_column('preferred_language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'english'"))
        batch_op.alter_column('adaptive_difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('adaptive_difficulty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
        batch_op.alter_column('preferred_language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'english'"))
        batch_op.alter_column('avatar',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'⚡'"))
        batch_op.alter_column('display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Hari'"))
        batch_op.alter_column('theme',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'light'"))
        batch_op.alter_column('api_provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'openai'"))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notifications_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_missions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_missions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_missions_review'), ['next_review_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_missions_date'), ['date'], unique=False)
        batch_op.alter_column('tags',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'english'"))

    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_completions_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_completions_mission_id'), ['mission_id'], unique=False)

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_bookmarks_mission_id'), ['mission_id'], unique=False)

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.alter_column('rarity',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'common'"))

    # ### end Alembic commands ###
