import { useEffect, useState } from "react";
import Topbar from "../components/Topbar";
import { getProfile, updateProfile, getDashboard, ProfileData, DashboardData, getReportCard, ReportCard, getPublicProfile, PublicProfile, openLootBox, LootBoxResult } from "../api/client";

const AVATARS = ["⚡", "🔥", "🎯", "🚀", "💎", "🌟", "🦁", "🐉", "🎮", "🧠", "💪", "🏆", "👑", "🌈", "🎸", "🦅"];

export default function Profile() {
  const [profile, setProfile] = useState<ProfileData | null>(null);
  const [dash, setDash] = useState<DashboardData | null>(null);
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState("");
  const [bio, setBio] = useState("");
  const [avatar, setAvatar] = useState("⚡");
  const [toast, setToast] = useState("");
  const [reportCard, setReportCard] = useState<ReportCard | null>(null);
  const [publicProfile, setPublicProfile] = useState<PublicProfile | null>(null);
  const [lootResult, setLootResult] = useState<LootBoxResult | null>(null);
  const [lootLoading, setLootLoading] = useState(false);

  const load = async () => {
    const [p, d] = await Promise.all([getProfile(), getDashboard()]);
    setProfile(p);
    setDash(d);
    setName(p.display_name);
    setBio(p.bio);
    setAvatar(p.avatar);
    getPublicProfile().then(setPublicProfile).catch(() => {});
  };

  useEffect(() => { load().catch(() => {}); }, []);

  const flash = (msg: string) => { setToast(msg); setTimeout(() => setToast(""), 3000); };

  const onSave = async () => {
    await updateProfile({ display_name: name, bio, avatar });
    setEditing(false);
    flash("Profile updated!");
    await load();
  };

  const onOpenLootBox = async () => {
    setLootLoading(true);
    try {
      const result = await openLootBox();
      setLootResult(result);
    } catch { flash("No loot box available."); }
    setLootLoading(false);
  };

  const onShareReport = async () => {
    try {
      const card = await getReportCard();
      setReportCard(card);
    } catch { flash("Failed to generate report card."); }
  };

  const downloadReportCard = () => {
    if (!reportCard) return;
    const canvas = document.createElement("canvas");
    canvas.width = 600;
    canvas.height = 400;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    // Background
    ctx.fillStyle = "#0F172A";
    ctx.fillRect(0, 0, 600, 400);
    ctx.fillStyle = "#16A34A";
    ctx.fillRect(0, 0, 600, 6);
    // Title
    ctx.fillStyle = "#F1F5F9";
    ctx.font = "bold 24px Inter, sans-serif";
    ctx.fillText("SkillForge", 30, 50);
    // Avatar & Name
    ctx.font = "36px serif";
    ctx.fillText(reportCard.avatar, 30, 100);
    ctx.fillStyle = "#F1F5F9";
    ctx.font = "bold 20px Inter, sans-serif";
    ctx.fillText(reportCard.display_name, 80, 95);
    ctx.fillStyle = "#94A3B8";
    ctx.font = "14px Inter, sans-serif";
    ctx.fillText(reportCard.rank + " | " + reportCard.week_label, 80, 115);
    // Stats
    const stats = [
      { label: "Total XP", value: reportCard.total_xp.toLocaleString() },
      { label: "Week XP", value: reportCard.week_xp.toLocaleString() },
      { label: "Missions", value: String(reportCard.week_missions) },
      { label: "Avg Score", value: String(reportCard.avg_score) },
      { label: "Streak", value: reportCard.current_streak + " days" },
    ];
    stats.forEach((s, i) => {
      const x = 30 + (i % 3) * 190;
      const y = 160 + Math.floor(i / 3) * 80;
      ctx.fillStyle = "#22C55E";
      ctx.font = "bold 28px Inter, sans-serif";
      ctx.fillText(s.value, x, y);
      ctx.fillStyle = "#94A3B8";
      ctx.font = "12px Inter, sans-serif";
      ctx.fillText(s.label, x, y + 20);
    });
    // Top skills
    ctx.fillStyle = "#F1F5F9";
    ctx.font = "bold 14px Inter, sans-serif";
    ctx.fillText("Top Skills", 30, 340);
    reportCard.top_skills.forEach((s, i) => {
      ctx.fillStyle = "#CBD5E1";
      ctx.font = "14px Inter, sans-serif";
      ctx.fillText(`${s.icon} ${s.name} (LVL ${s.level})`, 30 + i * 180, 365);
    });
    // Watermark
    ctx.fillStyle = "#475569";
    ctx.font = "11px Inter, sans-serif";
    ctx.fillText("Generated by SkillForge", 380, 390);
    // Download
    const link = document.createElement("a");
    link.download = `skillforge-report-${new Date().toISOString().slice(0, 10)}.png`;
    link.href = canvas.toDataURL();
    link.click();
    flash("Report card downloaded!");
  };

  if (!profile) return (<><Topbar title="Profile" totalXp={0} rank="Rookie" rankProgressPct={0} nextRankXp={500} streak={0} streakMultiplier={1} /><main className="content"><div className="card" style={{ color: "var(--text-muted)" }}>Loading<span className="loading-dots" /></div></main></>);

  return (
    <>
      <Topbar title="Profile" totalXp={dash?.total_xp || 0} rank={dash?.rank || "Rookie"} rankProgressPct={dash?.rank_progress_pct || 0} nextRankXp={dash?.next_rank_xp || 500} streak={dash?.current_streak || 0} streakMultiplier={dash?.streak_multiplier || 1} />
      <main className="content">
        {/* Profile Header */}
        <div className="card" style={{ textAlign: "center", padding: "30px 20px", marginBottom: 14 }}>
          <div style={{ fontSize: 48, marginBottom: 8 }}>{profile.avatar}</div>
          <h2 style={{ margin: "0 0 4px", fontSize: 20, fontWeight: 800 }}>{profile.display_name}</h2>
          <p style={{ color: "var(--text-dim)", fontSize: 13, margin: 0 }}>{profile.bio || "No bio yet"}</p>
          <div style={{ marginTop: 12, display: "flex", justifyContent: "center", gap: 16 }}>
            <span style={{ fontSize: 12, color: "var(--green)", fontWeight: 700 }}>{profile.rank}</span>
            <span style={{ fontSize: 12, color: "var(--text-dim)" }}>{profile.total_xp.toLocaleString()} XP</span>
            <span style={{ fontSize: 12, color: "var(--orange)", fontWeight: 600 }}>{profile.current_streak} day streak</span>
          </div>
          <div style={{ marginTop: 12, display: "flex", justifyContent: "center", gap: 8 }}>
            <button className="btn btn-outline" onClick={() => setEditing(true)}>Edit Profile</button>
            <button className="btn btn-primary" onClick={onShareReport}>Share Report Card</button>
          </div>
        </div>

        {/* Stats Grid */}
        <div className="stats-grid">
          <div className="stat-card"><div className="stat-icon" style={{ background: "#DCFCE7" }}>&#9889;</div><div className="stat-value">{profile.total_xp.toLocaleString()}</div><div className="stat-label">Total XP</div></div>
          <div className="stat-card"><div className="stat-icon" style={{ background: "#DBEAFE" }}>&#127919;</div><div className="stat-value">{profile.total_missions}</div><div className="stat-label">Missions</div></div>
          <div className="stat-card"><div className="stat-icon" style={{ background: "#FEF3C7" }}>&#128293;</div><div className="stat-value">{profile.longest_streak}</div><div className="stat-label">Best Streak</div></div>
          <div className="stat-card"><div className="stat-icon" style={{ background: "#F3E8FF" }}>&#127942;</div><div className="stat-value">{profile.achievements_unlocked}/{profile.achievements_total}</div><div className="stat-label">Achievements</div></div>
        </div>

        {/* Report Card Modal */}
        {reportCard && (
          <div className="modal-backdrop" onClick={() => setReportCard(null)}>
            <div className="confirm-modal" style={{ textAlign: "center", maxWidth: 420 }} onClick={(e) => e.stopPropagation()}>
              <div style={{ fontSize: 36, marginBottom: 8 }}>{reportCard.avatar}</div>
              <h3>{reportCard.display_name}'s Report Card</h3>
              <p style={{ color: "var(--text-dim)", fontSize: 12 }}>{reportCard.rank} | {reportCard.week_label}</p>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, margin: "16px 0" }}>
                <div><div style={{ fontSize: 20, fontWeight: 800, color: "var(--green)" }}>{reportCard.week_xp}</div><div style={{ fontSize: 10, color: "var(--text-muted)" }}>Week XP</div></div>
                <div><div style={{ fontSize: 20, fontWeight: 800 }}>{reportCard.week_missions}</div><div style={{ fontSize: 10, color: "var(--text-muted)" }}>Missions</div></div>
                <div><div style={{ fontSize: 20, fontWeight: 800 }}>{reportCard.avg_score}</div><div style={{ fontSize: 10, color: "var(--text-muted)" }}>Avg Score</div></div>
              </div>
              <div style={{ display: "flex", gap: 8, justifyContent: "center" }}>
                <button className="btn btn-primary" onClick={downloadReportCard}>Download Image</button>
                <button className="btn btn-outline" onClick={() => setReportCard(null)}>Close</button>
              </div>
            </div>
          </div>
        )}

        {/* Edit Modal */}
        {editing && (
          <div className="modal-backdrop" onClick={() => setEditing(false)}>
            <div className="confirm-modal" onClick={(e) => e.stopPropagation()}>
              <h3>Edit Profile</h3>
              <div style={{ marginBottom: 12 }}>
                <label style={{ fontSize: 12, fontWeight: 600, color: "var(--text-dim)", display: "block", marginBottom: 4 }}>Avatar</label>
                <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                  {AVATARS.map((a) => (
                    <button key={a} onClick={() => setAvatar(a)} style={{ fontSize: 24, padding: 6, borderRadius: 8, border: avatar === a ? "2px solid var(--green)" : "2px solid transparent", background: avatar === a ? "var(--green-bg)" : "transparent", cursor: "pointer" }}>{a}</button>
                  ))}
                </div>
              </div>
              <div style={{ marginBottom: 12 }}>
                <label style={{ fontSize: 12, fontWeight: 600, color: "var(--text-dim)", display: "block", marginBottom: 4 }}>Display Name</label>
                <input value={name} onChange={(e) => setName(e.target.value)} maxLength={50} />
              </div>
              <div style={{ marginBottom: 16 }}>
                <label style={{ fontSize: 12, fontWeight: 600, color: "var(--text-dim)", display: "block", marginBottom: 4 }}>Bio</label>
                <textarea value={bio} onChange={(e) => setBio(e.target.value)} maxLength={200} rows={3} style={{ width: "100%", resize: "vertical" }} />
              </div>
              <div className="row" style={{ gap: 8, justifyContent: "flex-end" }}>
                <button className="btn btn-outline" onClick={() => setEditing(false)}>Cancel</button>
                <button className="btn btn-primary" onClick={onSave}>Save</button>
              </div>
            </div>
          </div>
        )}

        {/* Public Profile Card (#43) */}
        {publicProfile && (
          <div className="public-profile-card">
            <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 16 }}>
              <div style={{ fontSize: 36 }}>{publicProfile.avatar}</div>
              <div>
                <h3>{publicProfile.display_name}</h3>
                <div className="muted">{publicProfile.rank} &middot; Member since {publicProfile.member_since}</div>
              </div>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12, marginBottom: 16 }}>
              <div><div style={{ fontSize: 18, fontWeight: 800, color: "#22C55E" }}>{publicProfile.total_xp.toLocaleString()}</div><div style={{ fontSize: 10, color: "#94A3B8" }}>XP</div></div>
              <div><div style={{ fontSize: 18, fontWeight: 800, color: "#FB923C" }}>{publicProfile.current_streak}</div><div style={{ fontSize: 10, color: "#94A3B8" }}>Streak</div></div>
              <div><div style={{ fontSize: 18, fontWeight: 800 }}>{publicProfile.total_missions}</div><div style={{ fontSize: 10, color: "#94A3B8" }}>Missions</div></div>
              <div><div style={{ fontSize: 18, fontWeight: 800 }}>{publicProfile.achievements_unlocked}</div><div style={{ fontSize: 10, color: "#94A3B8" }}>Achievements</div></div>
            </div>
            {publicProfile.top_skills.length > 0 && (
              <div>
                <div style={{ fontSize: 11, fontWeight: 700, color: "#94A3B8", marginBottom: 6, textTransform: "uppercase" }}>Top Skills</div>
                <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
                  {publicProfile.top_skills.map((s, i) => (
                    <span key={i} style={{ fontSize: 12, padding: "4px 10px", borderRadius: 6, background: "rgba(255,255,255,0.1)", color: "#F1F5F9" }}>
                      {s.icon} {s.name} LVL {s.level}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Loot Box (#30) */}
        <div className="card" style={{ marginTop: 14, textAlign: "center", padding: "20px" }}>
          <div style={{ fontSize: 36, marginBottom: 8 }}>&#127873;</div>
          <div style={{ fontWeight: 700, marginBottom: 4 }}>Loot Box</div>
          <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 12 }}>Open a mystery box to receive random rewards!</div>
          <button className="btn btn-primary" onClick={onOpenLootBox} disabled={lootLoading}>
            {lootLoading ? "Opening..." : "Open Loot Box"}
          </button>
        </div>

        {/* Loot Box Result Modal */}
        {lootResult && (
          <div className="modal-backdrop" onClick={() => setLootResult(null)}>
            <div className="confirm-modal loot-box-result" onClick={(e) => e.stopPropagation()}>
              <div className="loot-icon">&#127873;</div>
              <h3>You received:</h3>
              <div style={{ fontSize: 24, fontWeight: 800, marginBottom: 4 }} className={`loot-rarity-${lootResult.item.rarity}`}>
                {lootResult.item.name}
              </div>
              <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 4, textTransform: "uppercase", fontWeight: 700 }}>
                {lootResult.item.rarity} {lootResult.item.type}
              </div>
              <button className="btn btn-primary" style={{ marginTop: 14 }} onClick={() => setLootResult(null)}>Awesome!</button>
            </div>
          </div>
        )}

        {toast && <div className="app-toast">{toast}</div>}
      </main>
    </>
  );
}
